# Generated by Django 6.1 on 2026-08-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_type',
            field=models.CharField(choices=[('journal', 'Journal Article'), ('conference', 'Conference Paper'), ('book', 'Book / Book Chapter'), ('report', 'Research Report'), ('working', 'Working Paper'), ('other', 'Other')], default='journal', max_length=20),
        ),
        migrations.AddField(
            model_name='publication',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
