# Generated by Django 6.1 on 2026-08-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0002_publication_featured_publication_publication_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('news', 'News'), ('event', 'Event'), ('research', 'Research'), ('recognition', 'Recognition'), ('announcement', 'Announcement')], default='news', max_length=30),
        ),
    ]
