# Generated by Django 6.1 on 2026-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0003_news_featured_news_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='publications/'),
        ),
    ]
