# Generated by Django 6.1 on 2026-08-23 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='github',
            new_name='ResearchGate',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='website',
            new_name='live_DNA',
        ),
    ]
