# Generated by Django 6.1 on 2026-08-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0006_rename_github_profile_researchgate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='orcid',
            new_name='ORCID',
        ),
    ]
