# Generated by Django 6.1 on 2026-08-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0007_rename_orcid_profile_orcid'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='google_scholar_url',
            field=models.URLField(blank=True, verbose_name='Google Scholar Link'),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal_url',
            field=models.URLField(blank=True, verbose_name='Journal Link'),
        ),
        migrations.AddField(
            model_name='publication',
            name='researchgate_url',
            field=models.URLField(blank=True, verbose_name='ResearchGate Link'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.URLField(blank=True, verbose_name='DOI Link'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_url',
            field=models.URLField(blank=True, verbose_name='Publication Link'),
        ),
    ]
