# Generated by Django 6.1 on 2026-08-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0008_publication_google_scholar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='category',
            field=models.CharField(choices=[('director', 'Director'), ('professor', 'Professor'), ('postdoc', 'Postdoctoral Researcher'), ('phd', 'PhD Student'), ('masters', "Master's Student"), ('undergraduate', 'Undergraduate Student'), ('research_assistant', 'Research Assistant'), ('visiting_scholar', 'Visiting Scholar'), ('visiting_student', 'Visiting Student'), ('alumni', 'Alumni'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
