# Generated by Django 6.1 on 2026-08-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0009_teammember_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='UpdateProfile',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
