# Generated by Django 6.1 on 2026-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0010_rename_profile_updateprofile_delete_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='download_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/', verbose_name='Full Text PDF'),
        ),
    ]
