# Generated by Django 6.1 on 2026-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0011_publication_download_count_publication_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='biography',
            field=models.TextField(blank=True),
        ),
    ]
