# Generated by Django 6.1 on 2026-08-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0012_alter_teammember_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='biography',
        ),
    ]
