# Generated by Django 6.1 on 2026-09-02 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0013_remove_teammember_biography'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='selected',
        ),
        migrations.AddField(
            model_name='publication',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of Upload'),
            preserve_default=False,
        ),
    ]
