# Generated by Django 6.1 on 2026-09-02 15:19

import Okonkwo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0014_remove_publication_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/', validators=[Okonkwo.models.validate_publication_file], verbose_name='Full Text File'),
        ),
    ]
