# Generated by Django 6.1 on 2026-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0015_alter_publication_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=300, verbose_name='Post Title')),
                ('label', models.CharField(max_length=100)),
                ('header_picture', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='Header Picture')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, verbose_name='Date of Upload')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date_uploaded'],
            },
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ResearchArea',
        ),
    ]
