# Generated by Django 6.1 on 2026-09-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0016_blogpost_delete_project_delete_researcharea'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Post Count'),
        ),
    ]
