# Generated by Django 6.1 on 2026-09-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0017_blogpost_post_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='abstract',
            field=models.TextField(blank=True, verbose_name='Abstract'),
        ),
    ]
