# Generated by Django 6.1 on 2026-09-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0019_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
