# Generated by Django 6.1 on 2026-09-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0020_blogcomment_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
