# Generated by Django 6.1 on 2026-09-16 16:17

import Okonkwo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0021_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='date_commented',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Commented'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='header_picture',
            field=models.FileField(blank=True, null=True, upload_to='blog/', validators=[Okonkwo.models.validate_blog_file], verbose_name='Post File'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/', verbose_name='Full Text File'),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
