# Generated by Django 6.1 on 2026-09-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0022_alter_blogcomment_date_commented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='category',
            field=models.CharField(default='other', max_length=100, verbose_name='Category'),
        ),
    ]
