# Generated by Django 6.1 on 2026-09-16 22:25

import Okonkwo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Okonkwo', '0023_alter_teammember_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='publications/pdfs/', validators=[Okonkwo.models.validate_publication_file], verbose_name='Full Text File'),
        ),
    ]
